name: Create Pull Request

on:
  create:

jobs:
  create:
    uses: heitorpolidoro/workflows/.github/workflows/create-pr.yml@master
    secrets:
      heitorpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}
