name: Create Pull Request

on:
  create:

jobs:
  create-PR:
    uses: heitorpolidoro/workflows/.github/workflows/create-pr.yml@master
    with:
      heitorpolidoro: ${{ secrets.HEITORPOLIDORO_PAT }}
