name: Visual Test

on:
  push:

jobs:
  test_commands:
    name: Test Commands
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: echo true
        run: echo '${{ steps.setup_python.outputs.cache-hit }}

      - name: echo not
        run: echo '${{ ! steps.setup_python.outputs.cache-hit }}

      - name: Install dependencies
        if: ${{ ! steps.setup_python.outputs.cache-hit }}"
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test Commands
        run: PYTHONPATH=. python tests/visual_tests.py

